version: '3'

services:
  blockscout:
    image: ${EXPLORER_IMAGE}
    build:
      context: .
      args:
        - COIN=${COIN}
    ports:
     - ${EXPLORER_EXPOSE_PORT}:${EXPLORER_PORT}
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - ETHEREUM_JSONRPC_VARIANT=${ETHEREUM_JSONRPC_VARIANT}
      - ETHEREUM_JSONRPC_HTTP_URL=${ETHEREUM_JSONRPC_HTTP_URL}
      - ETHEREUM_JSONRPC_WS_URL=${ETHEREUM_JSONRPC_WS_URL}
    extra_hosts: 
      - host.docker.internal:host-gateway
    entrypoint: '/bin/sh -c "mix do ecto.create, ecto.migrate; mix phx.server"'
    depends_on:
      - postgres
    restart: on-failure
  
  postgres:
    image: ${DB_IMAGE}
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_DB}
    ports:
      - ${DB_EXPOSE_PORT}:${DB_PORT}
